package com.julioplacas.modelo;

public enum Estado {
  TURNO_JUGADOR_1,
  TURNO_JUGADOR_2,
  VICTORIA_JUGADOR_1,
  VICTORIA_JUGADOR_2,
  DESCONEXION_JUGADOR_1,
  DESCONEXION_JUGADOR_2,
  DESCONEXION_AMBOS,
}
